#!/bin/sh

case "$1" in
	start)
		printf "Starting perccmd: "
		killall -SIGINT PercCmd
		/media/BOOT/perccmd.sh >/dev/null 2>&1 &
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		printf "Stopping percmd: "
		killall -SIGINT PercCmd
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	restart|reload)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0

